fix:Fix the way items in the  legend of the doughnut chart are display
makerdao-ses/ecosystem-dashboard pull request #1364
Opened 2024-03-08 20:24 UTC by alejandrocabriales

Fix the number items that should show to get better aproach of the space At the moment the items display but some cases don't got the correct space

## Ticket

## Description

## What solved
- [X] FR 1 item
- [X] FR 2 item...

## Screenshots (if apply)

2024-03-10 17:56 UTC, YasielCabrera requested changes

2024-03-10 17:56 UTC, YasielCabrera commented on src/stories/containers/Finances/components/OverviewCardKeyDetailsBudget/DoughnutChartFinances/ItemLegendDoughnut.tsx
> +// );
did you miss to delete this code?

2024-03-11 11:36 UTC, alejandrocabriales commented on src/stories/containers/Finances/components/OverviewCardKeyDetailsBudget/DoughnutChartFinances/ItemLegendDoughnut.tsx
> +// );
My bad, the comment are already delete

2024-03-11 13:55 UTC, YasielCabrera approved these changes
lgtm

2024-03-11 13:55 UTC, merged