SES 222 feature cookie issue storybook
makerdao-ses/ecosystem-dashboard pull request #502
Opened 2023-01-16 17:43 UTC by alejandrocabriales

# Ticket
https://trello.com/c/vl1Dc2j6/222-feature-cookie-issue

# Actions
Add storybook checkbox
Add is-Light as props test storybook
Add storybook banner policy and correct props is-Light in Custom Button

2023-01-17 13:41 UTC, YasielCabrera requested changes

2023-01-17 13:41 UTC, YasielCabrera commented on src/stories/components/cookies-policy-banner/cookies-policy-banner.tsx
> +  // isShowBanner: boolean;
if this property is not used then should be completely removed

2023-01-17 13:59 UTC, YasielCabrera requested changes
There are unwanted changes on other components

2023-01-17 13:59 UTC, YasielCabrera commented on src/stories/components/custom-button/custom-button.tsx
> +      ...props.style,
note that this added unwanted changes to the auditor comment form component. You can see the visual change on chromatic

2023-01-17 20:11 UTC, YasielCabrera requested changes

2023-01-17 20:11 UTC, YasielCabrera commented on src/stories/components/check-box/check-box.stories.tsx
> +export const [[Checked, Unchecked]] = createThemeModeVariants(CheckBox, variantsArgs);
Please, note that `createThemeModeVariants` return 2 stories for each item in `variantsArgs`. The expected return value for your case would be:

```js
export const [[Checked, CheckedDarkMode], [Unchecked, UncheckedDarkMode]] = createThemeModeVariants(CheckBox, variantsArgs);
```

2023-01-31 12:01 UTC, YasielCabrera approved these changes
LGTM

2023-01-31 12:08 UTC, alejandrocabriales commented on src/stories/components/cookies-policy-banner/cookies-policy-banner.stories.tsx
> +      viewports: [1194 | 375],
not problem, fixed

2023-01-31 12:17 UTC, YasielCabrera approved these changes

2023-01-31 12:17 UTC, merged