Feature/create modal component
makerdao-ses/ecosystem-dashboard pull request #809
Opened 2023-06-06 15:34 UTC by alejandrocabriales

# What solved
✅Should  create a modal component

# Actions
Add builder and category interface
Add a story for an item of modal open
Add style to the subcategory

2023-06-06 20:12 UTC, YasielCabrera requested changes

2023-06-06 20:12 UTC, YasielCabrera commented on src/stories/components/BasicModal/ChekBoxDescription/ChekBoxDescription.tsx
> +// import { IconButton } from '@mui/material';
is this necessary?

2023-06-07 01:28 UTC, alejandrocabriales commented on src/stories/components/BasicModal/ChekBoxDescription/ChekBoxDescription.tsx
> +// import { IconButton } from '@mui/material';
Not, remove

2023-06-07 01:32 UTC, YasielCabrera approved these changes
LGTM

2023-06-07 02:09 UTC, merged