Add better transition in the header component
makerdao-ses/ecosystem-dashboard pull request #941
Opened 2023-08-05 16:25 UTC by alejandrocabriales

# Ticket
https://trello.com/c/FEo923dc/277-qa-bug-finding-r

# What solved
- [X] Add better transition to the header component

# Description
This adds a better transition to the header component

2023-08-06 01:50 UTC, YasielCabrera requested changes

2023-08-06 01:50 UTC, YasielCabrera commented on src/stories/components/CoreUnitSummary/CoreUnitSummary.tsx
> +    // height: !hiddenTextDescription ? 74 : 'fit-content',
did you forgot to delete this line?

2023-08-07 12:22 UTC, alejandrocabriales commented on src/stories/components/CoreUnitSummary/CoreUnitSummary.tsx
> +    // height: !hiddenTextDescription ? 74 : 'fit-content',
yes, its done now

2023-08-08 01:58 UTC, YasielCabrera approved these changes
lgtm

2023-08-08 02:06 UTC, merged